Add clockwise check for polygon
bigladder/kiva pull request #46
Opened 2022-02-28 20:35 UTC by matthew-larson

This pull request creates a bool function checking whether the polygon is counterclockwise, otherwise it is modified to satisfy this requirement.  A unit test was added for this condition.  The document also reformatted for clang.

2022-02-28 21:35 UTC, nealkruis requested changes

2022-02-28 21:35 UTC, nealkruis commented on test/unit/foundation.unit.cpp
> +}
What do we expect here? There are no tests (e.g., `EXPECT_TRUE()`).

2022-02-28 21:36 UTC, nealkruis requested changes

2022-02-28 21:36 UTC, nealkruis commented on src/libkiva/Foundation.cpp
> +      boost::geometry::correct(polygon);
We should issue a warning here.

2022-02-28 22:44 UTC, matthew-larson commented on test/unit/foundation.unit.cpp
> +}
Prior to the fix, it crashes in this function.  The same is done in the validation test.  Is there an EXPECT I can use in this situation where is basically passes by not crashing?  I did add a comment to "Expect success" as done previoiusly.

2022-02-28 22:51 UTC, matthew-larson commented on src/libkiva/Foundation.cpp
> +      boost::geometry::correct(polygon);
How is: `showMessage(MSG_WARN, "Surface was modified to be counterclockwise as required in Kiva.");`

2022-03-02 16:12 UTC, nealkruis commented on src/libkiva/Foundation.cpp
> +      boost::geometry::correct(polygon);
Sounds good!

2022-03-02 16:13 UTC, nealkruis commented on src/libkiva/Foundation.cpp
> +      boost::geometry::correct(polygon);
Actually, the term "Surface" is a little ambiguous in Kiva. Maybe say "Foundation floor polygon was modified ...".

2022-03-02 16:16 UTC, nealkruis commented on test/unit/foundation.unit.cpp
> +}
How about: `EXPECT_TRUE(isCounterClockwise(fnd.polygon))`?

2022-03-08 15:31 UTC, nealkruis approved these changes

2022-03-08 15:31 UTC, merged