Add werror option
bigladder/kiva pull request #55
Opened 2022-08-18 21:52 UTC by galanCA

## Description

The goal is to have the option to turn warnings into errors by 

### Major changes:

- Add compiler-flag.cmake and an interface library to distribute the compiler flags
- Add the option to turn off and on Werror (/WX for windows).

2022-08-18 21:53 UTC, galanCA commented
@nealkruis 
- what should be the default option for `KIVA_WERROR`?
- Would you like the CI to have Werror ON or OFF?

2022-08-18 21:59 UTC, nealkruis commented
I go back and forth on the default. I think I want it on by default, and then executables linking to Kiva can decide if they want to turn it off.

Definitely needs to be on for the CI, otherwise it won't keep us from merging warnings.

2022-08-19 17:01 UTC, nealkruis requested changes

2022-08-19 17:01 UTC, nealkruis commented on cmake/compiler-flags.cmake
> +target_compile_options(kiva_common_interface INTERFACE
I'm having second thoughts about this. Making these `INTERFACE` options means that they will propagate all the way up to the linking executable whether it wants them or not. Can you come up with a DRY way to apply these as `PRIVATE` options on the individual targets?

2022-08-19 17:01 UTC, nealkruis commented on CMakeLists.txt
> +option( KIVA_WERROR "Turn on warnings into error" ON )
I changed my mind on this one. Let's make it default to OFF, and handle things similarly to the [fmt repository](https://github.com/fmtlib/fmt).

2022-08-19 17:51 UTC, nealkruis commented on cmake/compiler-flags.cmake
> +target_compile_options(kiva_common_interface INTERFACE
Actually...I think you can leave this how it is, but make sure the targets that link to it set it as `PRIVATE`.

2022-08-19 17:52 UTC, nealkruis commented on cmake/compiler-flags.cmake
> +>
This is WET.

2022-08-25 20:53 UTC, galanCA commented
@nealkruis I tested that the interface library was only applied to the corresponding target by:
- Creating a new branch in CSE where:
  - I checkout this branch for kiva
  - make sure to turn on the WX flag in Kiva
  - and turn CSE warning flag from W3 to W4
From this, I would expect the CSE warnings to turn into errors if the WX flags were passed to CSE. But I was able to see the warnings and no errors allowing CSE to build successfully.

I went back and added the ability to turn on `KIVA_WERROR` option inside `vendor/cmakelist.txt` and check the `CMakeCache.txt`. But the output was the same as before, I could see the warnings, no errors and CSE build successfully. From this, I can derive that the interface library is only affecting the private target and not the dependencies of the target. 

Do you agree with this conclusion?

2022-08-30 14:27 UTC, nealkruis requested changes
Getting very close. I left two comments, but I think we are also missing a link to the common interface on one of the targets.

2022-08-30 14:27 UTC, nealkruis commented on src/libgroundplot/CMakeLists.txt
> +target_link_libraries(groundplot fmt mgl-static libkiva kiva_common_interface)
No keyword?

2022-08-30 14:27 UTC, nealkruis commented on src/kiva/CMakeLists.txt
> +target_link_libraries(kiva libkiva groundplot boost_program_options yaml-cpp kiva_common_interface)
No keyword?

2022-08-31 21:59 UTC, nealkruis approved these changes

2022-08-31 21:59 UTC, merged