reduce boost size
bigladder/kiva pull request #63
Opened 2023-07-06 17:45 UTC by spahrenk

## Description

- boost bcp utility used to eliminate unused files

## Author Progress Checklist:

- [x] Open draft pull request
    - [x] Make title clearly understandable in a standalone change log context
    - [x] Assign yourself the issue
    - [x] Add at least one label (enhancement, bug, or maintenance)
    - [x] Link the issue(s) addressed by this PR (under "Development" in the sidebar menu) 
- [x] Make code changes (if you haven't already)
- [x] Self-review of code
    - [x] My code follows the style guidelines of this project
    - [x] I have added comments to my code, particularly in hard-to-understand areas
    - [x] I have only committed the necessary changes for this fix or feature
    - [x] I have made corresponding changes to the documentation
    - [x] My changes generate no new warnings
    - [x] I have ensured that my fix is effective or that my feature works as intended by:
        - [x] exercising the code changes in the test framework, and/or
        - [x] manually verifying the changes (as explained in the the pull request description above)
    - [x] My changes pass all local tests
    - [ ] My changes successfully passes CI checks
    - [ ] Add any unit test for proof and documentation.
    - [ ] Merge in main branch and address resulting conflicts and/or test failures.
- [ ] Move pull request out of draft mode and assign reviewers
- [ ] Iterate with reviewers until all changes are approved
    - [ ] Make changes in response to reviewer comments
    - [ ] Merge in main branch and address resulting conflicts and/or test failures.
    - [ ] Re-request review in GitHub

## Reviewer Checklist:

 - [ ] Read the pull request description
 - [ ] Perform a code review on GitHub
 - [ ] Confirm all CI checks pass and there are no build warnings
 - [ ] Pull, build, and run automated tests locally
 - [ ] Perform manual tests of the fix or feature locally
 - [ ] Add any review comments, if applicable
 - [ ] Submit review in GitHub as either
     - [ ] Request changes, or
     - [ ] Approve
 - [ ] Iterate with author until all changes are approved

2023-07-13 15:30 UTC, nealkruis requested changes

2023-07-13 15:30 UTC, nealkruis commented on src/libkiva/Geometry.hpp
> +#pragma GCC system_header
This is maybe too broad of a solution. What are the specific warnings that came up? Is it specific to a recent version of GCC? Are the boost developers aware of the warning?

2023-07-13 15:30 UTC, nealkruis commented on scripts/update-boost.py
> +repo_path = docs_path + "/GitHub/kiva"
This seems specific to your machine's setup. It should be generalized to work on any machine and any platform.

2023-07-24 19:06 UTC, spahrenk commented
Modified script for cross-platform compatibility. Reverted to boost-1.81.0 to avoid compile warning in later version.

2023-07-24 19:08 UTC, spahrenk commented on src/libkiva/Geometry.hpp
> +#pragma GCC system_header
Used boost macros to disable quadmath and avoid warnings.

2023-07-24 19:09 UTC, spahrenk commented on scripts/update-boost.py
> +repo_path = docs_path + "/GitHub/kiva"
Changed script to enable command-line use and cross-platform compatibility.

2023-07-24 19:10 UTC, spahrenk commented
Reverted to boost-1.81.0 to avoid compiler warning in 1.82.0

2023-07-31 19:15 UTC, tanaya-mankad commented on scripts/update-boost.py
> +			file_list = file_list + " \"" + full_filename + "\""
I don't think the string `file_list` is subsequently used.

2023-07-31 19:48 UTC, tanaya-mankad requested changes

2023-07-31 19:48 UTC, tanaya-mankad commented on scripts/update-boost.py
> +	if platform.system() == "Windows":
I'm pretty sure that this is not an intended use of platform.system(). :) Have a look at Python's pathlib library for platform-independent, object-oriented path names. But I think the os.path module also should be able to deal with this natively.

2023-08-02 17:03 UTC, tanaya-mankad commented on scripts/update-boost.py
>  	file_list = ""
This is probably an unused variable now.

2023-08-02 19:51 UTC, tanaya-mankad requested changes

2023-08-02 19:51 UTC, tanaya-mankad commented on scripts/update-boost.py
> +	if os.path.exists(stash_boost_path + "/CMakeLists.txt"):
I would make a couple more changes for clarity. 
Combining os.path.abspath (or relpath) with os.path.join would make full path names a little more maintainable. Even though os.path treats paths as strings, we should strive to use its methods rather than depend on string literals that hard-code the "path-y" elements, like slashes.

2023-08-10 22:04 UTC, spahrenk commented
update-boost.py modified to use os.path.join for concatenation.

2023-08-15 20:12 UTC, tanaya-mankad requested changes

2023-08-15 20:12 UTC, tanaya-mankad commented on scripts/update-boost.py
>  def updateBoost(bcp_command, source_boost_path, repo_path, prev_repo_boost_folder_name, dest_repo_boost_folder_name):
`update_boost `for self-consistent (and PEP8 compliant) naming

2023-08-15 20:12 UTC, tanaya-mankad commented on scripts/update-boost.py
> +		print("\"" + os.path.join(stash_boost_path, "CMakeLists.txt") + "\" does not exist")
We should probably avoid repeating the literal `os.path.join(stash_boost_path, "CMakeLists.txt")` so many times.

2023-08-15 20:12 UTC, tanaya-mankad commented on scripts/update-boost.py
> +	if os.path.exists(os.path.join(stash_boost_path, "libs/program_options/CMakeLists.txt")):
`os.path.join(stash_boost_path, "libs/program_options/CMakeLists.txt")` isn't taking full advantage of join. Better would be `os.path.join(stash_boost_path, "libs", "program_options", "CMakeLists.txt")`
(See also above comment about repeating.)

2023-08-16 15:10 UTC, spahrenk commented
Calls to os.path.join were reorganized and reduced for clarity. Displayed status reports were changed to conform with the format used by bcp and for uniformity. Heading notes were altered for consistency and to incorporate latter changes.

2023-08-16 17:21 UTC, tanaya-mankad approved these changes
One last quick thing: (since it hadn't changed in a recent commit, I wonder if Github skipped putting my comment in the review...)
Line 95 `updateBoost `should probably be `update_boost `for self-consistency.

2023-08-17 14:56 UTC, spahrenk commented
Renamed updateBoost->update_boost

2024-08-29 14:34 UTC, closed without merging